# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='has_been_kicked',
            field=models.BooleanField(default=False),
        ),
    ]
