# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_chat', '0002_chatmember_has_been_kicked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmember',
            old_name='has_been_kicked',
            new_name='is_banned',
        ),
    ]
