# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sigma_chat.models.message


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_chat', '0004_auto_20161002_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(upload_to=sigma_chat.models.message.chat_directory_path)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='sigma_chat.Chat')),
                ('chatmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmember_message', to='sigma_chat.ChatMember')),
            ],
        ),
    ]
