# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import sigma_chat.models.message


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_chat', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to=sigma_chat.models.message.chat_directory_path),
        ),
    ]
