# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_chat', '0007_auto_20161002_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chatmember',
            new_name='chatmember_id',
        ),
    ]
